batch_size: 32
epochs: 40

image_encoder: efficientnet_v2_s
image_weight_path: outputs/model_best.pt

meg_encoder: eeg

loss: topk

device: cuda:0
num_workers: 8
seed: 1234
use_wandb: True

balanced_sampling: False

data_dir: data

# Evaluation
model_path: