batch_size: 128
epochs: 40
lr: 0.001

image_encoder: efficientnet_v2_s
image_weight_path: /root/outputs/2024-07-08/20-51-06/model_best.pt

# loss: topk 
loss: ce

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: data

# Evaluation
model_path: outputs/2024-07-09/10-39-15/model_best.pt